ALTER TABLE dbo."Users"
    ALTER COLUMN "DateRegister" TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN "LockoutEnabledDate" TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN "LockoutEndDate" TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN "LastAutorization" TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN "DateCreatedMark" TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN "SubscriptionStartDate" TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN "SubscriptionEndDate" TYPE TIMESTAMP WITH TIME ZONE;