INSERT INTO roles.project_roles (role_name, role_sys_name)
VALUES ('Доступ к настройкам проекта', 'ProjectSettings'),
       ('Доступ к настройкам представления', 'ProjectStrategySettings'),
       ('Создание задачи (любого типа)', 'ProjectCreateTask'),
       ('Изменение задачи (любого типа)', 'ProjectEditTaskSettings'),
       ('Доступ к задаче (любого типа)', 'ProjectTaskSettings'),
       ('Создание отчетов', 'ProjectCreateReport'),
       ('Изменение отчетов', 'ProjectEditReport'),
       ('Формирование отчетов', 'ProjectDownloadReport'),
       ('Удаление отчетов', 'ProjectRemoveReport'),
       ('Доступ к отчетам', 'ProjectReport'),
       ('Доступ к дашбордам', 'ProjectChart'),
       ('Дорожные карты проекта', 'ProjectRoadmap'),
       ('Создание дорожной карты проекта', 'ProjectCreateRoadmap'),
       ('Изменение дорожной карты проекта', 'ProjectEditRoadmap'),
       ('Удаление дорожной карты проекта', 'ProjectRemoveRoadmap'),
       ('Релизы', 'ProjectRelease'),
       ('Формирование релиза', 'ProjectCreateRelease'),
       ('Изменение релиза', 'ProjectEditRelease'),
       ('Удаление релиза', 'ProjectRemoveRelease'),
       ('Доступ к Wiki', 'ProjectWiki'),
       ('Создание папки Wiki', 'ProjectCreateFolderWiki'),
       ('Изменение папки Wiki', 'ProjectEditFolderWiki'),
       ('Удаление папки Wiki', 'ProjectRemoveFolderWiki'),
       ('Создание страницы Wiki', 'ProjectCreatePageWiki'),
       ('Изменение страницы Wiki', 'ProjectEditPageWiki'),
       ('Удаление страницы Wiki', 'ProjectRemovePageWiki'),
       ('Доступ к проекту', 'ProjectAccess'),
       ('Доступ к компании', 'OrganizationAccess'),
       ('Доступ к спринтам', 'SprintAccess'),
       ('Создание спринта', 'SprintCreate'),
       ('Изменение спринта', 'SprintEdit'),
       ('Удаление спринта', 'SprintRemove');