INSERT INTO rules.fare_rule_attribute_values (rule_id, is_price, attribute_id, "position", measure, min_value, max_value, is_range, content_tooltip, content)
VALUES (1, FALSE, 2, 2, 'До ', 5, NULL, FALSE, NULL, NULL),
       (1, FALSE, 3, 3, NULL, NULL, NULL, FALSE, NULL, 'Этапы/стадии проекта'),
       (1, FALSE, 3, 4, NULL, NULL, NULL, FALSE, NULL, 'Создание и управление задачами'),
       (1, FALSE, 3, 5, NULL, NULL, NULL, FALSE, NULL, 'Подзадачи/чек-листы'),
       (1, FALSE, 3, 6, NULL, NULL, NULL, FALSE, NULL, 'Взаимосвязи между задачами'),
       (1, FALSE, 3, 7, NULL, NULL, NULL, FALSE, NULL, 'Назначение ответственных'),
       (1, FALSE, 3, 8, NULL, NULL, NULL, FALSE, NULL, 'Соисполнители и наблюдатели'),
       (1, FALSE, 3, 9, NULL, NULL, NULL, FALSE, NULL, 'Kanban-стратегия представления (доска)'),
       (1, FALSE, 3, 10, NULL, NULL, NULL, FALSE, NULL, 'Scrum-представления представления (список)'),
       (1, FALSE, 3, 11, NULL, NULL, NULL, FALSE, NULL, 'Gantt-представление (график на временной шкале)'),
       (1, FALSE, 3, 12, NULL, NULL, NULL, FALSE, NULL, 'Уведомления о задачах'),
       (1, FALSE, 3, 13, NULL, NULL, NULL, FALSE, NULL, 'Комментарии к задачам'),
       (1, FALSE, 3, 14, NULL, NULL, NULL, FALSE, NULL, 'Чат проекта'),
       (1, FALSE, 3, 15, NULL, NULL, NULL, FALSE, NULL, 'Приглашения/добавление участников в проект'),
       (1, FALSE, 3, 16, NULL, NULL, NULL, FALSE, NULL, 'Календарь'),
       (1, FALSE, 4, 17, NULL, NULL, NULL, FALSE, NULL, 'Бесплатно'),
       (1, FALSE, 5, 18, ' руб. за вакансию', 499, NULL, FALSE, NULL, NULL),
       (1, FALSE, 6, 19, ' чтобы открыть контакт', 99, NULL, FALSE, NULL, NULL),

       (2, FALSE, 2, 20, NULL, 6, 10, TRUE, 'Все, что включает Бесплатный +', NULL),
       (2, FALSE, 3, 21, NULL, 6, 10, TRUE, NULL, 'Шаблоны проектов'),
       (2, FALSE, 3, 21, NULL, 6, 10, TRUE, NULL, 'Шаблоны задач'),
       (2, FALSE, 3, 22, NULL, 6, 10, TRUE, NULL, 'Поиск задач по фильтрам'),
       (2, FALSE, 3, 23, NULL, 6, 10, TRUE, NULL, 'Онбординг проекта (регламенты)'),
       (2, FALSE, 3, 24, NULL, 6, 10, TRUE, NULL, 'Интеграция календаря с Google-календарем'),
       (2, FALSE, 3, 25, NULL, 6, 10, TRUE, NULL, 'Интеграции с Telegram'),

       (2, TRUE, 4, 26, ' руб. за каждого человека', 299, NULL, FALSE, NULL, NULL),
       (2, TRUE, 5, 27, ' руб. за вакансию', 899, NULL, FALSE, NULL, NULL),
       (2, TRUE, 6, 27, ' руб., чтобы открыть контакт', 399, NULL, FALSE, NULL, NULL),

       (2, FALSE, 2, 20, NULL, 6, 10, TRUE, 'Все, что включает Бесплатный +', NULL),
       (2, FALSE, 3, 21, NULL, 6, 10, TRUE, NULL, 'Шаблоны проектов'),
       (2, FALSE, 3, 21, NULL, 6, 10, TRUE, NULL, 'Шаблоны задач'),
       (2, FALSE, 3, 22, NULL, 6, 10, TRUE, NULL, 'Поиск задач по фильтрам'),
       (2, FALSE, 3, 23, NULL, 6, 10, TRUE, NULL, 'Онбординг проекта (регламенты)'),
       (2, FALSE, 3, 24, NULL, 6, 10, TRUE, NULL, 'Интеграция календаря с Google-календарем'),
       (2, FALSE, 3, 25, NULL, 6, 10, TRUE, NULL, 'Интеграции с Telegram'),

       (3, TRUE, 2, 26, NULL, 11, 50, TRUE, 'Все, что включает Стартовый +', NULL),
       (3, TRUE, 3, 27, NULL, NULL, NULL, FALSE, NULL, 'Визуальная доска'),
       (3, TRUE, 3, 28, NULL, NULL, NULL, FALSE, NULL, 'Создание потребности на подбор сотрудников'),
       (3, TRUE, 3, 29, NULL, NULL, NULL, FALSE, NULL, 'Гостевой доступ к проекту и задачам'),
       (3, TRUE, 4, 30, ' руб. за каждого человека', 329, NULL, FALSE, NULL, 'Гостевой доступ к проекту и задачам'),
       (3, TRUE, 5, 31, ' руб. за вакансию', 899, NULL, FALSE, NULL, 'Бесплатно'),
       (3, TRUE, 6, 32, ' руб., чтобы открыть контакт', 399, NULL, FALSE, NULL, 'Бесплатно'),

       (4, TRUE, 2, 33, NULL, NULL, NULL, FALSE, NULL, NULL),
       (4, TRUE, 3, 33, NULL, NULL, NULL, FALSE, 'Все, что включает Основной + ', NULL),
       (4, TRUE, 3, 34, NULL, NULL, NULL, FALSE, NULL, 'Размещение вакансии из блока «Вакансии»'),
       (4, TRUE, 3, 35, NULL, NULL, NULL, FALSE, NULL, 'Размещение вакансии прямо из проекта'),
       (4, TRUE, 3, 36, NULL, NULL, NULL, FALSE, NULL, 'Просмотр резюме'),
       (4, TRUE, 4, 37, ' руб. за каждого человека', 899, NULL, FALSE, NULL, NULL),
       (4, TRUE, 5, 38, NULL, NULL, NULL, FALSE, NULL, NULL),
       (4, TRUE, 6, 39, NULL, NULL, NULL, FALSE, NULL, NULL);